service: sls-test-ml-model

provider:
  name: aws
  region: ap-northeast-1
  runtime: python2.7

functions:
  datarobot:
    handler: handler.predict
    memorySize: 128
    events:
      - http:
          path: predict
          method: post
  status:
    handler: status.status
    memorySize: 128
    events:
      - http:
          path: status
          method: get


custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements
